name: Black Format

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Checking the code format with Black
        run: |
          python -m black --check $(git ls-files '*.py')
